language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
  - php: hhvm
    dist: trusty

sudo: false

branches:
 only:
  - master

before_script:
  - composer self-update
  - composer install

script: 
  - vendor/bin/phpunit
