language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - hhvm-3.12
      env:
        global:
          - HHVMPHP7 = 1
    - hhvm-3.13
      env:
        global:
        - HHVMPHP7 = 1

sudo: false

branches:
 only:
  - master

before_script:
  - composer self-update
  - composer install

script: 
  - vendor/bin/phpunit
