language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

branches:
 only:
  - master

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls